import { Thread, Channel, User } from '../types';

export const mockUsers: Record<string, User> = {
    satoshi: {
        id: '1',
        username: 'satoshi_nakamoto',
        karma: 21000,
        satsTipped: 500000,
        satsEarned: 1000000,
        role: 'admin',
        badges: ['OG', 'Builder', 'Legend'],
        streak: 365,
    },
    alice: {
        id: '2',
        username: 'alice_lightning',
        karma: 5420,
        satsTipped: 120000,
        satsEarned: 250000,
        role: 'builder',
        badges: ['Lightning Dev', 'Early Adopter'],
        streak: 89,
    },
    bob: {
        id: '3',
        username: 'bob_hodler',
        karma: 2100,
        satsTipped: 45000,
        satsEarned: 78000,
        role: 'user',
        badges: ['Hodler'],
        streak: 21,
    },
    carol: {
        id: '4',
        username: 'carol_btc',
        karma: 8750,
        satsTipped: 200000,
        satsEarned: 420000,
        role: 'builder',
        badges: ['Core Contributor', 'BIP Author'],
        streak: 156,
    },
    david: {
        id: '5',
        username: 'david_miner',
        karma: 3200,
        satsTipped: 67000,
        satsEarned: 145000,
        role: 'user',
        badges: ['Mining Expert', 'Educator'],
        streak: 42,
    },
};

export const channels: Channel[] = [
    { id: 'dev', name: 'Dev', description: 'Technical discussions and development', icon: '⚙️', color: 'hsl(var(--bitcoin-orange))', threadCount: 1247 },
    { id: 'markets', name: 'Markets', description: 'Price action, trading, macro', icon: '📈', color: 'hsl(var(--accent))', threadCount: 3891 },
    { id: 'lightning', name: 'Lightning', description: 'Layer 2, payments, channels', icon: '⚡', color: 'hsl(var(--primary))', threadCount: 892 },
    { id: 'culture', name: 'Culture', description: 'Memes, art, community vibes', icon: '🎨', color: 'hsl(45 100% 51%)', threadCount: 2456 },
    { id: 'mining', name: 'Mining', description: 'Hash power, energy, infrastructure', icon: '⛏️', color: 'hsl(var(--muted-foreground))', threadCount: 654 },
    { id: 'education', name: 'Education', description: 'Learn, teach, grow together', icon: '📚', color: 'hsl(200 80% 60%)', threadCount: 1789 },
];

export const mockThreads: Thread[] = [
    {
        id: '1',
        title: 'What\'s the best way to learn Bitcoin development in 2024?',
        author: mockUsers.alice,
        content: 'I\'ve been following Bitcoin for a while and want to start contributing to the ecosystem. What\'s the recommended learning path? Should I start with the Bitcoin Core codebase, or are there better entry points?',
        timestamp: new Date(Date.now() - 1000 * 60 * 45),
        channel: 'Development',
        upvotes: 42,
        downvotes: 3,
        replyCount: 8,
        sats: 15000,
        tags: ['development', 'learning', 'resources'],
        replies: [
            {
                id: 'r1',
                author: mockUsers.bob,
                content: 'Start with "Mastering Bitcoin" by Andreas Antonopoulos. Then move to the Bitcoin dev docs and small contributions to test frameworks.',
                timestamp: new Date(Date.now() - 1000 * 60 * 30),
                upvotes: 28,
                downvotes: 1,
                sats: 5000,
                isTopAnswer: true,
            },
            {
                id: 'r2',
                author: mockUsers.carol,
                content: 'I\'d also recommend chaincode labs seminars and bitcoin optech newsletter for staying current.',
                timestamp: new Date(Date.now() - 1000 * 60 * 20),
                upvotes: 15,
                downvotes: 0,
                sats: 2000,
                replies: [
                    {
                        id: 'r2-1',
                        author: mockUsers.alice,
                        content: 'Thanks! I\'ll check those out. The optech newsletter looks perfect.',
                        timestamp: new Date(Date.now() - 1000 * 60 * 15),
                        upvotes: 5,
                        downvotes: 0,
                        sats: 500,
                    }
                ]
            },
        ]
    },
    {
        id: '2',
        title: 'Lightning Network capacity just hit 5000 BTC',
        author: mockUsers.david,
        content: 'The total Lightning Network capacity has reached a new all-time high of 5000 BTC. This is a significant milestone for scaling Bitcoin payments.',
        timestamp: new Date(Date.now() - 1000 * 60 * 120),
        channel: 'Lightning',
        upvotes: 156,
        downvotes: 8,
        replyCount: 23,
        sats: 45000,
        tags: ['lightning', 'capacity', 'milestone'],
        isHot: true,
    },
    {
        id: '3',
        title: 'Should I mine Bitcoin in 2024?',
        author: mockUsers.bob,
        content: 'Considering getting into mining. Is it still profitable for home miners, or is it only viable at scale now?',
        timestamp: new Date(Date.now() - 1000 * 60 * 180),
        channel: 'Mining',
        upvotes: 67,
        downvotes: 12,
        replyCount: 34,
        sats: 8000,
        tags: ['mining', 'profitability', 'hardware'],
    },
    {
        id: '4',
        title: 'New BIP proposal: Better fee estimation',
        author: mockUsers.carol,
        content: 'I\'ve been working on a BIP for improved fee estimation algorithms. Would love feedback from the community before submitting.',
        timestamp: new Date(Date.now() - 1000 * 60 * 240),
        channel: 'Development',
        upvotes: 89,
        downvotes: 5,
        replyCount: 15,
        sats: 25000,
        tags: ['bip', 'fees', 'development'],
        isPinned: true,
    },
    {
        id: '5',
        title: 'Best practices for cold storage in 2024',
        author: mockUsers.david,
        content: 'What are the current best practices for securing large amounts of Bitcoin? Hardware wallets, multisig, or something else?',
        timestamp: new Date(Date.now() - 1000 * 60 * 300),
        channel: 'Security',
        upvotes: 234,
        downvotes: 6,
        replyCount: 56,
        sats: 67000,
        tags: ['security', 'storage', 'wallets'],
        isHot: true,
    },
];

export const dailyQuestion = {
    id: 'daily-1',
    question: 'Should Bitcoin have a formal governance model?',
    description: 'Top answer gets 21,000 sats',
    bounty: 21000,
    deadline: new Date(Date.now() + 18 * 60 * 60 * 1000),
    responses: 134,
};

export const hotTakes = [
    {
        id: 'take-1',
        content: 'Layer 2s don\'t need to talk to each other. They need to talk to Bitcoin. Interoperability is a distraction from the real work.',
        author: mockUsers.satoshi,
        upvotes: 421,
        threadTitle: 'Should Layer 2s be interoperable?',
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
    {
        id: 'take-2',
        content: 'The Lightning Network isn\'t a scaling solution. It\'s a completely new financial paradigm. We\'re building the nervous system of money.',
        author: mockUsers.alice,
        upvotes: 389,
        threadTitle: 'Lightning Network capacity just hit 6000 BTC',
        timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    },
    {
        id: 'take-3',
        content: 'If you\'re not running your own node, you\'re not really using Bitcoin. You\'re using someone else\'s Bitcoin.',
        author: mockUsers.bob,
        upvotes: 267,
        threadTitle: 'What is your Bitcoin origin story?',
        timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000),
    },
];

export const opportunities = [
    {
        id: 'opp-1',
        type: 'job',
        title: 'Senior Lightning Engineer',
        organization: 'Strike',
        location: 'Remote',
        sats: 0,
        url: '#',
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
        id: 'opp-2',
        type: 'bounty',
        title: 'Build a BIP-300 reference implementation',
        organization: 'LayerTwo Labs',
        sats: 500000,
        url: '#',
        timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    },
    {
        id: 'opp-3',
        type: 'event',
        title: 'Bitcoin++',
        organization: 'Austin, TX',
        location: 'May 2-4, 2025',
        url: '#',
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    },
    {
        id: 'opp-4',
        type: 'grant',
        title: 'OpenSats Developer Grant',
        organization: 'OpenSats',
        sats: 2100000,
        url: '#',
        timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    },
];
