import { ExploreItem } from "./data";

// Static recommendation data for archetype-specific content
// This is separate from the main explore data which is now dynamic from Supabase
export const recommendationsData: ExploreItem[] = [
  {
    id: "satoshi-nakamoto",
    realId: "satoshi-nakamoto",
    title: "Satoshi Nakamoto",
    description: "The enigmatic creator of Bitcoin, whose identity remains one of the greatest mysteries in tech history.",
    type: "creator",
    category: "Creators",
    tags: ["founder", "mystery", "legend", "genesis"],
    image_url: "photo-1581090464777-f3220bbe1b8b",
  },
  {
    id: "hal-finney",
    realId: "hal-finney",
    title: "Hal Finney",
    description: "Cryptographic pioneer and the first person to receive a Bitcoin transaction from Satoshi Nakamoto.",
    type: "creator",
    category: "Creators",
    tags: ["pioneer", "cryptography", "early adopter", "cypherpunk"],
    image_url: "photo-1488590528505-98d2b5aba04b",
  },
  {
    id: "genesis-block-art",
    realId: "genesis-block-art",
    title: "Genesis Block Art",
    description: "Artistic interpretations of Bitcoin's first block, capturing the revolutionary moment that started it all.",
    type: "artifact",
    category: "Artifacts",
    tags: ["genesis", "digital art", "history", "blockchain"],
    image_url: "photo-1487058792275-0ad4aaf24ca7",
  },
  {
    id: "hodl-meme",
    realId: "hodl-meme",
    title: "HODL Forever",
    description: "The legendary typo that became Bitcoin's most famous investment strategy and cultural phenomenon.",
    type: "meme",
    category: "Memes",
    tags: ["meme", "strategy", "community", "viral"],
    image_url: "photo-1526374965328-7f61d46190af475",
  },
  {
    id: "pizza-day",
    realId: "pizza-day",
    title: "Bitcoin Pizza Day",
    description: "The first real-world Bitcoin transaction: 10,000 BTC for two pizzas, establishing Bitcoin's monetary value.",
    type: "meme",
    category: "Memes",
    tags: ["history", "transaction", "milestone", "pizza"],
    image_url: "photo-1500375592092-40eb206044001-80022131f5a1",
  },
  {
    id: "digital-gold",
    realId: "digital-gold",
    title: "Digital Gold",
    description: "The narrative that positioned Bitcoin as the digital equivalent of gold, a store of value for the internet age.",
    type: "meme",
    category: "Memes",
    tags: ["gold", "store of value", "scarcity", "narrative"],
    image_url: "photo-1488972685288-c3fd157d7c7a",
  },
  {
    id: "lightning-network",
    realId: "lightning-network",
    title: "Lightning Network",
    description: "The second-layer solution that enables instant Bitcoin payments, visualized through stunning network art.",
    type: "artifact",
    category: "Artifacts",
    tags: ["scaling", "payments", "network", "innovation"],
    image_url: "photo-1487058792275-0ad4aaf24ca7",
  },
  {
    id: "nick-szabo",
    realId: "nick-szabo",
    title: "Nick Szabo",
    description: "Computer scientist and cryptographer who created 'Bit Gold,' a precursor to Bitcoin's design.",
    type: "creator",
    category: "Creators",
    tags: ["bit gold", "cryptography", "smart contracts", "precursor"],
    image_url: "photo-1488590528505-98d2b5aba04b",
  },
  {
    id: "cypherpunk-manifesto",
    realId: "cypherpunk-manifesto",
    title: "Cypherpunk Culture",
    description: "The philosophical movement that birthed Bitcoin, advocating for privacy and cryptographic freedom.",
    type: "meme",
    category: "Memes",
    tags: ["cypherpunk", "privacy", "freedom", "philosophy"],
    image_url: "photo-1526374965328-7f61d46190af475",
  },
  {
    id: "diamond-hands",
    realId: "diamond-hands",
    title: "Diamond Hands",
    description: "The symbol of unwavering conviction in Bitcoin, representing those who hold through any market condition.",
    type: "meme",
    category: "Memes",
    tags: ["conviction", "holding", "strength", "community"],
    image_url: "photo-1581090464777-f3220bbe1b8b",
  },
  {
    id: "adam-back",
    realId: "adam-back",
    title: "Adam Back",
    description: "Creator of Hashcash, the proof-of-work system that became fundamental to Bitcoin's design.",
    type: "creator",
    category: "Creators",
    tags: ["hashcash", "proof of work", "cryptography", "blockstream"],
    image_url: "photo-1488590528505-98d2b5aba04b",
  },
  {
    id: "number-go-up",
    realId: "number-go-up",
    title: "Number Go Up",
    description: "The simple yet powerful meme that captures Bitcoin's price appreciation and community optimism.",
    type: "meme",
    category: "Memes",
    tags: ["price", "optimism", "growth", "simple"],
    image_url: "photo-1500375592092-40eb206044001-80022131f5a1",
  }
];
